2023-11-23 16:10:52,025 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:17:24,701 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:17:31,707 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:20:34,375 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:21:05,600 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:22:46,661 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:24:42,079 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:25:06,427 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:30:35,948 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:30:42,872 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:30:59,012 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:32:15,388 ERROR: Exception on /user/spusza14 [GET] [in /home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/Desktop/microblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts, form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/arch/Desktop/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/arch/Desktop/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/Desktop/microblog/app/templates/user.html", line 13, in block 'content'
    {% elif not current_user.is_following(user) %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/Desktop/microblog/app/models.py", line 52, in is_following
    followers.c.followed_id == user.id).count() > 0
    ^^^^^^^^^
NameError: name 'followers' is not defined. Did you mean: 'self.followers'?
2023-11-23 16:35:41,719 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:35:49,045 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:36:45,043 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:51:30,688 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:51:35,273 ERROR: Exception on /explore [GET] [in /home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/Desktop/microblog/app/routes.py", line 141, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
            ^^^^
NameError: name 'Post' is not defined
2023-11-23 16:51:37,243 ERROR: Exception on /index [GET] [in /home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/.local/share/rtx/installs/python/3.12.0/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arch/Desktop/microblog/app/routes.py", line 20, in index
    form = PostForm()
           ^^^^^^^^
NameError: name 'PostForm' is not defined
2023-11-23 16:52:22,437 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:52:46,066 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:52:49,953 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:53:41,849 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 16:58:07,979 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 17:01:01,297 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 17:01:04,552 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:46]
2023-11-23 17:08:32,262 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:29:41,381 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:29:50,865 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:30:43,683 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:32:07,236 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:46:51,532 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:47:05,978 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:57:24,112 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-23 17:57:33,677 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:48]
2023-11-24 14:31:06,822 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:50]
2023-11-24 14:32:21,362 INFO: Microblog startup [in /home/arch/Desktop/microblog/app/__init__.py:50]
